name: Main workflow

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ocaml: [4.00.0, 4.09.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: |
          git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Install OCaml and run test
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add ocaml $GITHUB_WORKSPACE
          asdf install ocaml ${{ matrix.ocaml }}
          asdf global ocaml ${{ matrix.ocaml }}
          ocaml -version
