name: Main workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ocaml: [4.00.0, 4.09.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Install ocaml and print ocaml version
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add ocaml $GITHUB_WORKSPACE
          asdf install ocaml ${{ matrix.ocaml }}
          asdf global ocaml ${{ matrix.ocaml }}
          ocaml -version

  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install asdf
        run: git clone https://github.com/asdf-vm/asdf.git $HOME/asdf

      - name: Test plugin
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . $HOME/asdf/asdf.sh
          asdf plugin-add ocaml $GITHUB_WORKSPACE
          bats test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run ShellCheck
        run: shellcheck bin/*
